<?php 

/**
 * Implementation of hook_block().
 *
 * @param $op What kind of information to retrieve about the block. Possible values: list, configure, save, view.
 * @param $delta Which block to return.
 * @param $edit Data from a configuration form, if submitted.
 */
function lagarto_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      $blocks[0] = array(
        'info' => t('Availability Checker'),
      ); 
      return $blocks;
    case 'configure':
      $form = array();
      
      return $form;
    case 'save':
      return;
    case 'view': default:
      switch ($delta) {
        case 0:
          $block['subject'] = t('Availability Checker');
          $block['content'] = t('Checks the availability of the rental property');
          break;
      }
      return $block;
  }
}

function lagarto_menu() {
  
  $items['admin/lagarto'] = array(
    'title' => 'Villa Lagarto',
    'description' => 'Administer Villa Lagarto.',
    'weight' => -8,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer site configuration'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );

 
  // TODO: contact morethanusdev.com about apc.shm_size=128M
  
  return $items;
}
